baseURL = 'https://positivity-news.github.io/'
languageCode = 'en-us'
title = 'Positivity News'
theme = 'clean_white'
[params]
      header_image = "img/Copy-of-pic.png"
[[params.addtional_menus]]
  title =  "ARCHIVE"
  href =  "/archive/"

